# Macro file for the visualization setting in the initialization phase 
# of the B1 example when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
/vis/open OGL

# Draw geometry:
/vis/drawVolume

/vis/viewer/set/autoRefresh true
/vis/viewer/set/style surface
/vis/scene/add/trajectories smooth
/vis/geometry/set/visibility worldLogic 0 false